declare const _default: {
  dataProvider: any;
  YPCCrypto: any;
  YPCNtObject: any;
  FileProvider: any;
  DirectDataEncoder: any;
  Sealer: any;
  ToString: any;
  dataHashOfSealedFile: any;
  signedDataHash: any;
  forwardSkey: any;
  calculateSealedHash: any;
  Unsealer: any;
  SealedFileStream: any;
  PipelineContext: any;
  PipelineContextInFile: any;
  RecoverableReadStream: any;
  RecoverableWriteStream: any;
};

export const DataProvider: typeof _default.dataProvider;
export const YPCCrypto: typeof _default.YPCCrypto;
export const YPCNtObject: typeof _default.YPCNtObject;
export const FileProvider: typeof _default.FileProvider;
export const DirectDataEncoder: typeof _default.DirectDataEncoder;
export const Sealer: typeof _default.Sealer;
export const ToString: typeof _default.ToString;
export const dataHashOfSealedFile: typeof _default.dataHashOfSealedFile;
export const signedDataHash: typeof _default.signedDataHash;
export const forwardSkey: typeof _default.forwardSkey;
export const calculateSealedHash: typeof _default.calculateSealedHash;
export const Unsealer: typeof _default.Unsealer;
export const SealedFileStream: typeof _default.SealedFileStream;
export const PipelineContext: typeof _default.PipelineContext;
export const PipelineContextInFile: typeof _default.PipelineContextInFile;
export const RecoverableReadStream: typeof _default.RecoverableReadStream;
export const RecoverableWriteStream: typeof _default.RecoverableWriteStream;
export default _default;
